services:
  mongo:
    image: mongo:5.0
    container_name: llm_engineering_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: llm_engineering
      MONGO_INITDB_ROOT_PASSWORD: llm_engineering
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.6.1
    container_name: llm_engineering_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
  qdrant_data:
